name: expensemanager
description:
  Expense Manager

version: 1.0.0+1

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  after_layout: ^1.0.7+2
  cloud_firestore: ^0.13.4
  collection: ^1.14.11
  encrypt: ^4.0.0
  firebase_analytics: ^5.0.11
  firebase_auth: ^0.15.5+2
  firebase_core: ^0.4.4+2
  firebase_messaging: ^6.0.12
  google_sign_in: ^4.1.4
  http: ^0.12.0+4
  intl: ^0.16.1
  json_annotation: ^3.0.1
  local_auth: ^0.6.1+3
  package_info: ^0.4.0+14
  path: ^1.6.4
  provider: ^4.0.4
  share: ^0.6.3+6
  shared_preferences: ^0.5.6+2
  sqflite: ^1.2.2
  transparent_image: ^1.0.0
  url_launcher: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.4
  flutter_launcher_icons: ^0.7.4
  intl_translation: ^0.17.9
  json_serializable: ^3.2.5

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/images/
    - assets/categories/expense/
    - assets/categories/income/
    - assets/categories/custom/
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/fonts/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu-BoldItalic.ttf
          weight: 600
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 700
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 800

flutter_icons:
  android: true
  ios: true
  image_path: assets/icons/app_icon.png

flutter_intl:
  enabled: true
